import { Product } from './validators'

// Catalog updated: 2025-09-21 at 14:30 - Force complete refresh
// CACHE BUSTER: Removed Zustand persistence - should load fresh data now
// Quiz Question Types
export interface QuizQuestion {
  id: string
  step: number
  type: 'single' | 'multi' | 'scale' | 'size'
  required: boolean
  label: string
  options?: string[]
  min?: number
  max?: number
  stepSize?: number
  sizeTypes?: string[]
  imageChoices?: boolean
}

// Catalog data loaded from CSV
export const catalogData: Product[] = [
  {
    "id": "470",
    "title": "Terra Knit Cable Sweater",
    "category": "maxi dress",
    "price": 74,
    "brand": "ALTAR'D STATE",
    "pattern": "knit",
    "sizes": [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "tags": [
      "new"
    ],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dwc7380f4b/image/001753_CC2171_MOCHA_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "575",
    "title": "Lucy Lace Trim Skirt",
    "category": "skirt",
    "price": 64,
    "brand": "ALTAR'D STATE",
    "pattern": "lace",
    "sizes": [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dwb818e759/image/004311_ASWB-251-375_BROWN-MULTI_09.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "430",
    "title": "Reese Leopard Vest",
    "category": "other",
    "price": 64,
    "brand": "ALTAR'D STATE",
    "pattern": "leopard",
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "tags": [
      "new"
    ],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dw6d699db1/image/001950_BT3534_LEOPARD_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "1187",
    "title": "Step Aside Layer",
    "category": "other",
    "price": 54,
    "brand": "AS REVIVAL",
    "pattern": "layered",
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dw0ff0d40b/image/000787_DZ25C921_RED_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "1292",
    "title": "Backwoods Camo Lounge Short",
    "category": "lounge",
    "price": 48,
    "brand": "AS REVIVAL",
    "pattern": "camouflage",
    "sizes": [
      "XS",
      "S",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dw1c0cead8/image/004293_SB2005C_CAMO_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "1282",
    "title": "Kick Back Lace Skort",
    "category": "other",
    "price": 58,
    "brand": "AS REVIVAL",
    "pattern": "lace",
    "sizes": [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dwbd96a879/image/004230_SK2389B-1_LT-HEATHER-GREY_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3029",
    "title": "Shilo Ribbed Cardigan",
    "category": "oversized sweater",
    "price": 28,
    "brand": "EDIKTED",
    "pattern": "ribbed",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Ai_test_Lookbook164926_a991b825-ce0e-442e-804a-5e440940dc41.jpg?v=1739228696&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "2551",
    "title": "Built In Bra Tube Top",
    "category": "tube top",
    "price": 12.6,
    "brand": "EDIKTED",
    "pattern": "other",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_06_13_202426731.jpg?v=1725183750&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "2786",
    "title": "Sasha Bow Detail Sweatpants",
    "category": "oversized sweater",
    "price": 31.2,
    "brand": "EDIKTED",
    "pattern": "bow detail",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_09_03_202459695_fb5a6ccb-83fa-46d6-ac5b-6ca4c263893b.jpg?v=1725644306&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3262",
    "title": "Lace Detail Denim Blazer",
    "category": "blazer",
    "price": 95.95,
    "brand": "Olivia TPS x NA-KD",
    "pattern": "denim",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/lace_detail_denim_blazer_1859-000003-0003_2_campaign.jpg?ref=2E6B190EF9",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3285",
    "title": "Knitted Pattern Sweater",
    "category": "sweater",
    "price": 85.95,
    "brand": "Olivia TPS x NA-KD",
    "pattern": "knit",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/knitted_pattern_sweater__1859-000009-0017_4_campaign.jpg?ref=50EF74A241",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3198",
    "title": "Wool Blend Fringe Detail Coat",
    "category": "coat",
    "price": 209.95,
    "brand": "Olivia TPS x NA-KD",
    "pattern": "wool",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/wool_blend_fringe_detail_coat_1859-000001-0124_3_campaign.jpg?ref=7321AF56DE",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3528",
    "title": "Mini Suede Crossbody Tote",
    "category": "mini dress",
    "price": 59.95,
    "brand": "NAKD",
    "pattern": "suede",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/mini_suede_crossbody_tote-1100-011470-0146_0040_creative.jpg?ref=2F76D9481E",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3297",
    "title": "Low Waist Jeans",
    "category": "coat",
    "price": 75.95,
    "brand": "NAKD",
    "pattern": "denim",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/low_waist_jeans_1018-008235-011684091_01c.jpg?ref=04B2FBFEC9",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3343",
    "title": "Flounce Waist Halterneck Maxi Dress",
    "category": "coat",
    "price": 85.95,
    "brand": "NAKD",
    "pattern": "halter",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/flounce_waist_halterneck_maxi_dress-1100-011401-0259_campaign_1.jpg?ref=3324F559D6",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3326",
    "title": "Oversized Long Trenchcoat",
    "category": "coat",
    "price": 149.95,
    "brand": "Josefine HJ x NA-KD",
    "pattern": "oversized",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/oversized_long_trenchcoat_1708-000079-8163_0020.jpg?ref=6E801791A7",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3206",
    "title": "Oversized Long Trenchcoat",
    "category": "coat",
    "price": 149.95,
    "brand": "Josefine HJ x NA-KD",
    "pattern": "oversized",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/oversized_long_trenchcoat_1708-000079-1844_0033.jpg?ref=62108E6F4C",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3217",
    "title": "Suede Boot",
    "category": "other",
    "price": 159.95,
    "brand": "Lovisa Wallin x NA-KD",
    "pattern": "suede",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/suede_boot_1757-000126-0017_1_campaign.jpg?ref=7D67D217E8",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3305",
    "title": "Small Suede Handbag",
    "category": "other",
    "price": 109.95,
    "brand": "Lovisa Wallin x NA-KD",
    "pattern": "suede",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/small_suede_handbag__1757-000125-0086_1_campaign.jpg?ref=67E9C6A49B",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3682",
    "title": "Structured Bow Detail Maxi Dress",
    "category": "maxi dress",
    "price": 129.95,
    "brand": "Lovisa Wallin x NA-KD",
    "pattern": "bow detail",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/structured_bow_detail_maxi_dress_1812-000917-0015_1_campaign.jpg?ref=33AEB127E6",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3241",
    "title": "Straight Stone Detail Denim",
    "category": "other",
    "price": 99.95,
    "brand": "Scandivv x NA-KD",
    "pattern": "denim",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/straight_stone_detail_denim_1812-001018-0003_campaign_campaign.jpg?ref=BD8861E5B6",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3352",
    "title": "Boxy Corduroy Shirt",
    "category": "other",
    "price": 59.95,
    "brand": "Shpresa x NA-KD",
    "pattern": "corduroy",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/boxy_cordueoy_shirt_1100-009658-001812217.jpg?ref=379C8EC82E",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3246",
    "title": "Boxy Corduroy Shirt",
    "category": "other",
    "price": 59.95,
    "brand": "Shpresa x NA-KD",
    "pattern": "corduroy",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/boxy_corduroy_shirt_1100-009658-02124_campaign.jpg?ref=0457C50973",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3461",
    "title": "Embroidered Long Sleeve Blouse",
    "category": "blouse",
    "price": 59.95,
    "brand": "Shpresa x NA-KD",
    "pattern": "embroidered",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/embroidered_long_sleeve_blouse_1100-011706-0801_24_campaign.jpg?ref=7F4ED871BA",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3299",
    "title": "Mid Waist Balloon Pants",
    "category": "pants",
    "price": 59.95,
    "brand": "Cecilie Haugaard x NA-KD",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/mid_waist_balloon_pants-1100-012439-0001_0013.jpg?ref=D6EB337326",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3497",
    "title": "Pleated Waist Long Sleeve Blouse",
    "category": "blouse",
    "price": 49.95,
    "brand": "Cecilie Haugaard x NA-KD",
    "pattern": "pleated",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/pleated_waist_long_sleeve_blouse_1100-011707-0005_1_campaign.jpg?ref=C350F5275A",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3277",
    "title": "Cotton Fitted Shirt",
    "category": "other",
    "price": 49.95,
    "brand": "Cecilie Haugaard x NA-KD",
    "pattern": "cotton",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/cotton_fitted_shirt_1100-011842-0001_1_campaign.jpg?ref=FBBD97C294",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3335",
    "title": "Open Back Maxi Dress",
    "category": "maxi dress",
    "price": 85.95,
    "brand": "Lydia Tomlinson x NA-KD",
    "pattern": "backless",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/open_back_maxi_dress_1812-001028-0001.jpg?ref=23A5D8AE67",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3576",
    "title": "Puff Sleeve Top",
    "category": "other",
    "price": 39.95,
    "brand": "Lydia Tomlinson x NA-KD",
    "pattern": "puff sleeve",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/puff_sleeve_top_1794-000076-0001.jpg?ref=CC2C0564D2",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3295",
    "title": "Flowy Knitted Midi Skirt",
    "category": "midi dress",
    "price": 59.95,
    "brand": "Lydia Tomlinson x NA-KD",
    "pattern": "knit",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/flowy_knitted_midi_skirt_1794-000089-0001.jpg?ref=BB81392E3D",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3600",
    "title": "Anglaise Straight Trousers",
    "category": "pants",
    "price": 59.95,
    "brand": "Michaela Wissén x NA-KD",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/anglaise_straight_trousers_1833-000007-4070_1_campaign.jpg?ref=73BE94A1E7",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3303",
    "title": "One Shoulder Back Detail Maxi Dress",
    "category": "maxi dress",
    "price": 95.95,
    "brand": "Michaela Wissén x NA-KD",
    "pattern": "one shoulder",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/one_shoulder_back_detail_maxi_dress_1833-000005-0198_8_campaign.jpg?ref=068AB5DEEC",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3395",
    "title": "Faux Suede Boxy Jacket",
    "category": "jacket",
    "price": 99.95,
    "brand": "Emmanuelle Koffi x NA-KD",
    "pattern": "suede",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/faux_suede_boxy_jacket_1858-000009-0212_campaign.jpg?ref=9080DCD504",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3572",
    "title": "Checked High Slit Maxi Dress",
    "category": "maxi dress",
    "price": 85.95,
    "brand": "Emmanuelle Koffi x NA-KD",
    "pattern": "plaid",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/checked_high_slit_maxi_dress_1858-000008-7733_3_campaign.jpg?ref=A9913C1DCE",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3455",
    "title": "Faux Suede Midi Skirt",
    "category": "midi dress",
    "price": 75.95,
    "brand": "Emmanuelle Koffi x NA-KD",
    "pattern": "suede",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/faux_suede_midi_skirt_1858-000010-0212_5_campaign.jpg?ref=38CA61E3E3",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3421",
    "title": "Leather Slouchy Handbag",
    "category": "other",
    "price": 95.95,
    "brand": "Camelia Farhoodi x NA-KD",
    "pattern": "leather",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/carolineeserup_1100-010691-0002_social.jpg?ref=17D7168261",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3511",
    "title": "Bandeau Pleated Maxi Dress",
    "category": "tube top",
    "price": 85.95,
    "brand": "Sofi Fahrman Engelbert x NA-KD",
    "pattern": "pleated",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/bandeau_big_pleat_maxi_dress_1781-000018-0041_0921_campaign.jpg?ref=E391F78406",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3457",
    "title": "Ripped Detail Denim Shirt",
    "category": "other",
    "price": 75.95,
    "brand": "Sofi Fahrman Engelbert x NA-KD",
    "pattern": "denim",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/ripped_detail_denim_shirt_1781-000027-0001_0943_campaign.jpg?ref=528B641751",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3463",
    "title": "Tie Front Puff Shoulder Blouse",
    "category": "blouse",
    "price": 49.95,
    "brand": "Claire Rose x NA-KD",
    "pattern": "tie detail",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/tie_front_puff_shoulder_blouse_1100-010458-0001_1_social.jpg?ref=6157D3CF17",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3581",
    "title": "Volume Mini Dress",
    "category": "mini dress",
    "price": 59.95,
    "brand": "Claire Rose x NA-KD",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/volume_mini_dress-1720-000161-00026660_01c.jpg?ref=15193B3C14",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3659",
    "title": "Tailored High Waist Shorts",
    "category": "shorts",
    "price": 39.95,
    "brand": "Claire Rose x NA-KD",
    "pattern": "high waist",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/tailored_high_waist_shorts-1720-000232-00170064.jpg?ref=61321956D9",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3533",
    "title": "Crochet Mini Dress",
    "category": "mini dress",
    "price": 59.95,
    "brand": "Emrata x NA-KD",
    "pattern": "crochet",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/crochet_mini_dress_1856-000018-0801_2_campaign.jpg?ref=67E0147819",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3555",
    "title": "Printed Linen Blend Pants",
    "category": "pants",
    "price": 59.95,
    "brand": "Moa Mattsson x NA-KD",
    "pattern": "linen",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/printed_linen_blend_pants__1812-001012-0259_12_campaign.jpg?ref=BD484C927F",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3544",
    "title": "Printed Linen Blend Shirt",
    "category": "other",
    "price": 59.95,
    "brand": "Moa Mattsson x NA-KD",
    "pattern": "linen",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/printed_linen_blend_shirt_1812-001011-0259_4_campaign.jpg?ref=DEA269D244",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3621",
    "title": "T-Strap Ballerinas",
    "category": "other",
    "price": 59.95,
    "brand": "NA-KD",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.na-kd.com/cdn-cgi/image/width=300,quality=80,sharpen=0.3/globalassets/t-strap_ballerinas_1100-011606-0017_2_campaign.jpg?ref=8D7A5A9004",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3861",
    "title": "Everyday Seamless Ribbed Midi Top",
    "category": "midi dress",
    "price": 34,
    "brand": "GYMSHARK",
    "pattern": "ribbed",
    "sizes": [],
    "tags": [
      "new"
    ],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0156/6146/files/images-EverydaySeamlessTrend1MidiTopGSCherryPurpleB4C3L_PCDS_1683_0600_3840x.jpg?v=1752765430",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3731",
    "title": "Activate Long Sleeve Crop Top",
    "category": "sports bra",
    "price": 50,
    "brand": "GYMSHARK",
    "pattern": "cropped",
    "sizes": [],
    "tags": [
      "new"
    ],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0156/6146/files/images-ActivateSeamlessLongSleeveCropTopGSPlumBrownB2C4Q_NBZN_0252_3840x.jpg?v=1754409287",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3713",
    "title": "Lifting Dipped Waistband Short",
    "category": "other",
    "price": 46,
    "brand": "GYMSHARK",
    "pattern": "other",
    "sizes": [],
    "tags": [
      "new"
    ],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0156/6146/files/images-LiftingDippedWaistbandShortGSBlackB4B8X_BB2J_0818_3840x.jpg?v=1755627221",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4401",
    "title": "Snuggle Up Sweater High-Waist Wide Leg Pant - Ivory",
    "category": "sweater",
    "price": 198,
    "brand": "ALO YOGA",
    "pattern": "high waist",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/2185/2813/files/W51431R_03299_b1_s1_a1_1_m54_320x.jpg?v=1734374188",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4351",
    "title": "Cropped All Day Short Sleeve - Black",
    "category": "crop top",
    "price": 58,
    "brand": "ALO YOGA",
    "pattern": "cropped",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/2185/2813/products/W1444R_01_b1_s1_a1_1_m18_320x.jpg?v=1697145019",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4115",
    "title": "Airlift Line Up Bra - Navy",
    "category": "other",
    "price": 88,
    "brand": "ALO YOGA",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/2185/2813/files/W9533R_03842_b2_s1_a1_1_m254_320x.jpg?v=1756165174",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4799",
    "title": "Dusk Till Dawn Chevron Bikini Set",
    "category": "set",
    "price": 35.99,
    "brand": "CUPSHE",
    "pattern": "chevron",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.cupshe.comdata:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4826",
    "title": "Just a Wink Aqua One-Piece Swimsuit",
    "category": "swimsuit",
    "price": 35.99,
    "brand": "CUPSHE",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.cupshe.comdata:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4828",
    "title": "Boho Floral Halter Tummy Control One-Piece Swimsuit",
    "category": "bikini set",
    "price": 40.99,
    "brand": "CUPSHE",
    "pattern": "floral",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://www.cupshe.comdata:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6141",
    "title": "Zuba Mini Dress Leopard",
    "category": "mini dress",
    "price": 15,
    "brand": "Princess Polly",
    "pattern": "leopard",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-natalya-us2_f629bfd5-7f66-4750-bc7f-c251e0ceb66f_639x866_crop_center.jpg?v=1724126608",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5741",
    "title": "Vixyn Halter Maxi Dress Red Multi",
    "category": "mini dress",
    "price": 85,
    "brand": "Princess Polly",
    "pattern": "halter",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-tianna-us2_d41559af-7ab5-4f71-870e-94b38a91756d_639x866_crop_center.jpg?v=1746570628",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5298",
    "title": "Landon Mini Dress Pink",
    "category": "mini dress",
    "price": 65,
    "brand": "Princess Polly",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-paris-us2_0d7dcaad-bbae-4a30-8fb8-3797a63fea7c_639x866_crop_center.jpg?v=1723172773",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6785",
    "title": "Capisce Maxi Dress Red Petite",
    "category": "mini dress",
    "price": 42,
    "brand": "Princess Polly Lower Impact",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-sinclair-us4_8365286e-ad73-4cf5-b1b6-8fe7030933c1_639x866_crop_center.jpg?v=1742536186",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6324",
    "title": "Rosalina Sheer Maxi Dress Pink",
    "category": "mini dress",
    "price": 11,
    "brand": "Princess Polly Lower Impact",
    "pattern": "mesh",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/2_8b7b43b6-86e0-4eb8-a79a-0969ca0fcc7d_639x866_crop_center.jpg?v=1727236595",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5283",
    "title": "Carette Strapless Mini Dress Hot Pink",
    "category": "mini dress",
    "price": 75,
    "brand": "Princess Polly Lower Impact",
    "pattern": "strapless",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-elly-us2_44468eee-54fb-42bd-9327-f740cc60994a_639x866_crop_center.jpg?v=1724909754",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6685",
    "title": "Sweeter Places Embroidered Mini Dress White Petite",
    "category": "mini dress",
    "price": 41,
    "brand": "Princess Polly Petite",
    "pattern": "lace",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-hailey-us4_ead53c9c-63c0-40f3-b356-8f724aa8247d_639x866_crop_center.jpg?v=1746760989",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6809",
    "title": "Mayok Mini Dress Grey Petite",
    "category": "mini dress",
    "price": 27.5,
    "brand": "Princess Polly Petite",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-nat-us2_34071ad1-f9db-4099-9a01-79490a2a805e_639x866_crop_center.jpg?v=1729207357",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5441",
    "title": "Moonlit Mini Dress Pink Stripe Petite",
    "category": "mini dress",
    "price": 65,
    "brand": "Princess Polly Petite",
    "pattern": "striped",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-holly-us2_394582e1-09c8-4b67-aef6-4f1c076158f4_639x866_crop_center.jpg?v=1739423851",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5309",
    "title": "Martini Mini Dress Porcelain",
    "category": "mini dress",
    "price": 69,
    "brand": "Lioness",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-emmah-us2_234934dc-a651-4de8-82d8-555abfd86a77_639x866_crop_center.jpg?v=1756789284",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5063",
    "title": "Girls Girls Girls Mini Dress White",
    "category": "mini dress",
    "price": 75,
    "brand": "Lioness",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-gaia-us2_bea74456-1654-4435-b010-bee4d87b69ac_639x866_crop_center.jpg?v=1741240408",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6468",
    "title": "Field Of Dreams Maxi Dress Crimson",
    "category": "maxi dress",
    "price": 57,
    "brand": "Lioness",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-elly-us2_c825ead3-bff7-4c73-814e-c6c069fd5212_639x866_crop_center.jpg?v=1739941895",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6814",
    "title": "Gigli Bubble Hem Mini Dress Black Tall",
    "category": "mini dress",
    "price": 30,
    "brand": "Princess Polly Tall",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/GIGLI-BUBBLE-HEM-MINI-DRESS-BLACK_98dbd15c-4376-4d62-be24-add1520947d3_639x866_crop_center.jpg?v=1729053717",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6772",
    "title": "Parisa Long Sleeve Mini Dress Black Tall",
    "category": "mini dress",
    "price": 28,
    "brand": "Princess Polly Tall",
    "pattern": "long sleeve",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-tatiana-us6_6193c5ea-5f91-4bb9-9331-0edd28366d3e_639x866_crop_center.jpg?v=1729213783",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5166",
    "title": "Galvis Mini Dress White Tall",
    "category": "mini dress",
    "price": 69,
    "brand": "Princess Polly Tall",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-nat-us2_dc517427-c72b-467b-b675-352f2320df45_639x866_crop_center.jpg?v=1716525914",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5373",
    "title": "Fayola Maxi Dress Floral Brown",
    "category": "maxi dress",
    "price": 84,
    "brand": "Motel",
    "pattern": "floral",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-Savannah-us2_d15bac13-d1ac-4e08-bef5-248ce6e59f13_639x866_crop_center.jpg?v=1752013732",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6651",
    "title": "Cryolan Mini Dress White",
    "category": "mini dress",
    "price": 16,
    "brand": "Motel",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-allie-us2_774a3f8d-a343-414c-8ad0-e2bc96592af2_639x866_crop_center.jpg?v=1720085689",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5390",
    "title": "Motel Lunama Dress Tonal Blue Paisley",
    "category": "dress",
    "price": 75,
    "brand": "Motel",
    "pattern": "paisley",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/products/0-modelinfo-saskia-us2_60e31729-ce67-42e9-812d-48c5aabc86c4_639x866_crop_center.jpg?v=1669602342",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5450",
    "title": "Imeraldia Hardware Halter Maxi Dress Currant Curve",
    "category": "mini dress",
    "price": 85,
    "brand": "Princess Polly Curve",
    "pattern": "halter",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-yasmine-us14_1e44c8b9-2339-4266-8806-f03f34f5deed_639x866_crop_center.jpg?v=1753765050",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6639",
    "title": "Lanai Maxi Dress Black Curve",
    "category": "mini dress",
    "price": 39.5,
    "brand": "Princess Polly Curve",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-mia-us14_ed42ed22-a27d-48fe-b942-176ef4de2dfb_639x866_crop_center.jpg?v=1723179203",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6870",
    "title": "Irena Strapless Maxi Dress Burgundy Curve",
    "category": "mini dress",
    "price": 39.5,
    "brand": "Princess Polly Curve",
    "pattern": "strapless",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-annabelle-us14_6aff7ccb-3187-4b93-a3b3-a22f4e727905_639x866_crop_center.jpg?v=1734650899",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5890",
    "title": "Sleep Schedule Sleep Mini Dress Pink Polka",
    "category": "mini dress",
    "price": 65,
    "brand": "Princess Polly Sleep",
    "pattern": "polka dot",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-rino-us4_091b98a8-eefd-4736-91f8-0561d4bb09da_639x866_crop_center.jpg?v=1753077144",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6574",
    "title": "Caprani Mini Dress Grey",
    "category": "mini dress",
    "price": 11,
    "brand": "Princess Polly Soft Fit",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/products/0-modelinfo-kiele-us4_140db89d-031f-4e9e-a23e-ba8a33ddb5aa_639x866_crop_center.jpg?v=1674453827",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6384",
    "title": "Adonis Mini Dress White",
    "category": "mini dress",
    "price": 14,
    "brand": "Princess Polly Soft Fit",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-jacelyn-us4_8aee173b-83dd-4d98-8700-c71297dfac2c_639x866_crop_center.jpg?v=1683152289",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6477",
    "title": "Ambition Activewear Romper Latte Curve",
    "category": "romper",
    "price": 9,
    "brand": "Princess Polly Active",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-riley-us14_54b929cc-4bcc-4391-95a4-3639dc831ba5_639x866_crop_center.jpg?v=1707190748",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "7449",
    "title": "Aston Rib Pant",
    "category": "other",
    "price": 108,
    "brand": "VUORI",
    "pattern": "ribbed",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/files/VW4069SPR_SP24_W_ECOMM_PANTS_FRONT_6.jpg?v=1715970130&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "7434",
    "title": "Vuori AllTheFeels™ Short 4",
    "category": "other",
    "price": 64,
    "brand": "VUORI",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/files/VW3052CPP_SP25_W_ECOMM_BOTTOMS_FRONT_2.jpg?v=1738624676&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "7145",
    "title": "Vuori AllTheForm™ Headband",
    "category": "other",
    "price": 22,
    "brand": "VUORI",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/files/VW857BLK_FA25_UNISEX_ECOMM_HEADWEAR_FLAT_LAY_1.jpg?v=1743438984&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "7352",
    "title": "Vuori AllTheForm™ Legging- Long",
    "category": "other",
    "price": 98,
    "brand": "VUORI",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/files/VW4130-LBVT_SP25_W_ECOMM_BOTTOMS_FRONT_1_327224e8-6492-4c85-a01e-986a5a24dfd6.jpg?v=1737679063&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6853",
    "title": "Delfie Strapless Mini Dress White",
    "category": "mini dress",
    "price": 17,
    "brand": "Princess Polly",
    "pattern": "strapless",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-selina-us2_e0c96dc7-fd6d-4c8a-82a2-3543b0f0e5ed_639x866_crop_center.jpg?v=1740634680",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "1622",
    "title": "Jagger Low Rise Denim Shorts",
    "category": "oversized sweater",
    "price": 39,
    "brand": "EDIKTED",
    "pattern": "denim",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_06_25_2025254904.jpg?v=1752024529&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5474",
    "title": "Allawah Halter Maxi Dress Red",
    "category": "mini dress",
    "price": 78,
    "brand": "Princess Polly Lower Impact",
    "pattern": "halter",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/1-modelinfo-adison-us4_c80f729b-e87a-4f22-8342-3ae45da17677_639x866_crop_center.jpg?v=1702942061",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5249",
    "title": "Mollins Long Sleeve Mini Dress Red",
    "category": "mini dress",
    "price": 27,
    "brand": "Princess Polly",
    "pattern": "long sleeve",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-summer-us2_e598aa06-a69a-4670-a2fd-be4fa2914ab3_639x866_crop_center.jpg?v=1733372837",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4223",
    "title": "Pinstripe Daylight Boxer Pant (Long) - Black/Titanium",
    "category": "other",
    "price": 148,
    "brand": "ALO YOGA",
    "pattern": "striped",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/2185/2813/files/W54328R_01407_b1_s1_a5_m125_320x.jpg?v=1754953638",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "3141",
    "title": "Yasmine Linen Look Pants",
    "category": "pants",
    "price": 29.6,
    "brand": "EDIKTED",
    "pattern": "linen",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_10_04_202491399.jpg?v=1729589740&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5714",
    "title": "Aspyn Halter Mini Dress Pink",
    "category": "mini dress",
    "price": 75,
    "brand": "Princess Polly Lower Impact",
    "pattern": "halter",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-mia-us4_cee7c818-333b-421a-a35e-07131c08a12c_639x866_crop_center.jpg?v=1750890726",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5101",
    "title": "Lukea Long Sleeve Mini Dress Navy",
    "category": "mini dress",
    "price": 69,
    "brand": "Princess Polly Lower Impact",
    "pattern": "long sleeve",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-cathlin-us2_2df9c370-ffd7-4cc7-ae1d-b66b9b9f3ebf_639x866_crop_center.jpg?v=1715649535",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "2170",
    "title": "Imani Satin Effect Tank Top",
    "category": "oversized sweater",
    "price": 25,
    "brand": "EDIKTED",
    "pattern": "satin",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_09_03_202460149copy.jpg?v=1725956066&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "2209",
    "title": "Katia V Neck Top",
    "category": "other",
    "price": 14.4,
    "brand": "EDIKTED",
    "pattern": "v-neck",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "tags": [],
    "imageUrl": "https://edikted.com/cdn/shop/files/Edikted_Lookbook_07_01_202429743copy.jpg?v=1722334993&width=600",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "7240",
    "title": "Halo Bodysuit",
    "category": "bodysuit",
    "price": 78,
    "brand": "VUORI",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/products/VW1112HST_SP23_W_ECOMM_TOPS_3923_1X1_1.jpg?v=1688710183&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "4690",
    "title": "Wool Cropped Metro Trench - Toasted Almond",
    "category": "crop top",
    "price": 228,
    "brand": "ALO YOGA",
    "pattern": "wool",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/2185/2813/files/W4627R_05131_b1_s1_a1_1_m18_320x.jpg?v=1746471749",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "569",
    "title": "Fortworth Texas Baby Tee",
    "category": "maxi dress",
    "price": 42,
    "brand": "ALTAR'D STATE",
    "pattern": "other",
    "sizes": [
      "XXS",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dw67a4f213/image/001890_A2724RE74JD_IVORY_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6696",
    "title": "Elmstead Strapless Romper Black",
    "category": "romper",
    "price": 30,
    "brand": "Princess Polly",
    "pattern": "strapless",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-olivia-us2_768e529e-424a-4cfe-825f-cd2791693ad8_639x866_crop_center.jpg?v=1735784644",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "1211",
    "title": "Roll Call Layer",
    "category": "other",
    "price": 64,
    "brand": "AS REVIVAL",
    "pattern": "layered",
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "tags": [],
    "imageUrl": "https://www.altardstate.com/dw/image/v2/BDDX_PRD/on/demandware.static/-/Sites-as_catalog/default/dw0a16056e/image/004430_MT37284_WHITE_00.JPG?sw=300&sh=450&q=98",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "5535",
    "title": "Dasha Mini Dress White Lower Impact",
    "category": "mini dress",
    "price": 69,
    "brand": "Princess Polly Lower Impact",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://us.princesspolly.com/cdn/shop/files/0-modelinfo-elise-us2_f5052ac7-4864-4581-92bb-3c754299d989_639x866_crop_center.jpg?v=1745267208",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  },
  {
    "id": "6984",
    "title": "Halo Essential Bra",
    "category": "other",
    "price": 48,
    "brand": "VUORI",
    "pattern": "other",
    "sizes": [],
    "tags": [],
    "imageUrl": "https://cdn.shopify.com/s/files/1/0022/4008/6074/files/VW1110HNM_FA25_W_ECOMM_BRAS_FRONT_3.jpg?v=1752697152&width=800&height=1000&crop=center",
    "fit": "regular",
    "colors": [],
    "gender": "unisex"
  }
]

export const quizQuestions = [
  {
    id: "categories",
    step: 1,
    type: "multi" as const,
    required: true,
    label: "What types of clothing are you looking for?",
    options: ["blouse", "blazer", "bodysuit", "coat", "crop top", "dress", "jacket", "lounge", "maxi dress", "midi dress", "mini dress", "other", "oversized sweater", "pants", "romper", "set", "shorts", "skirt", "sports bra", "sweater", "swimsuit", "tube top", "bikini set"]
  },
  {
    id: "colors",
    step: 2,
    type: "multi" as const,
    required: true,
    label: "What colors do you prefer?",
    options: ["black", "white", "navy", "grey", "beige", "pink", "red", "green", "blue", "purple", "brown"]
  },
  {
    id: "brands",
    step: 3,
    type: "multi" as const,
    required: true,
    label: "Which brands do you like?",
    options: ["ALO YOGA", "ALTAR'D STATE", "AS REVIVAL", "CUPSHE", "EDIKTED", "GYMSHARK", "Lioness", "Motel", "NAKD", "Princess Polly", "Princess Polly Active", "VUORI"]
  },
  {
    id: "styles",
    step: 4,
    type: "multi" as const,
    required: true,
    label: "Which styles appeal to you?",
    options: ["casual", "formal", "sporty", "trendy", "classic", "minimalist", "bohemian", "edgy", "romantic"],
    imageChoices: true
  },
  {
    id: "size",
    step: 5,
    type: "single" as const,
    required: true,
    label: "What's your size?",
    options: ["3XL", "L", "M", "S", "S/M", "XL", "XS", "XS/S", "XXL", "XXS"]
  },
  {
    id: "budget",
    step: 6,
    type: "scale" as const,
    required: true,
    label: "What's your maximum budget per item?",
    min: 6.8,
    max: 698.0,
    stepSize: 10
  }
]
